"""角色名称

遵照格式： id: [台服官译简体, 日文原名, 英文名(罗马音), B服官译, 常见别称, 带错别字的别称等] （<-依此顺序）
若暂无台服官译则用日文原名占位，台日用全角括号，英文用半角括号
"""
CHARA_NAME = {
    1: ['妙蛙种子', 'Bulbasaur'],
    2: ['妙蛙草', 'Ivysaur'],
    3: ['妙蛙花', 'Venusaur'],
    4: ['小火龙', 'Charmander'],
    5: ['火恐龙', 'Charmeleon'],
    6: ['喷火龙', 'Charizard', '老喷'],
    7: ['杰尼龟', 'Squirtle'],
    8: ['卡咪龟', 'Wartortle'],
    9: ['水箭龟', 'Blastoise'],
    10: ['绿毛虫', 'Caterpie'],
    11: ['铁甲蛹', 'Metapod'],
    12: ['巴大蝶', 'Butterfree'],
    13: ['独角虫', 'Weedle'],
    14: ['铁壳蛹', 'Kakuna'],
    15: ['大针蜂', 'Beedrill'],
    16: ['波波', 'Pidgey'],
    17: ['比比鸟', 'Pidgeotto'],
    18: ['大比鸟', 'Pidgeot'],
    19: ['小拉达', 'Rattata'],
    19001: ['小拉达(阿罗拉)', 'Rattata_a'],
    20: ['拉达', 'Raticate'],
    20001: ['拉达(阿罗拉)', 'Raticate_1'],
    21: ['烈雀', 'Spearow'],
    22: ['大嘴雀', 'Fearow'],
    23: ['阿柏蛇', 'Ekans'],
    24: ['阿柏怪', 'Arbok'],
    25: ['皮卡丘', 'Pikachu'],
    26: ['雷丘', 'Raichu'],
    26001: ['雷丘(阿罗拉)', 'Raichu_a'],
    27: ['穿山鼠', 'Sandshrew'],
    27001: ['穿山鼠(阿罗拉)', 'Sandshrew_a'],
    28: ['穿山王', 'Sandslash'],
    28001: ['穿山王(阿罗拉)', 'Sandslash_a'],
    29: ['尼多兰', 'Nidoran♀'],
    30: ['尼多娜', 'Nidorina'],
    31: ['尼多后', 'Nidoqueen'],
    32: ['尼多朗', 'Nidoran♂'],
    33: ['尼多力诺', 'Nidorino'],
    34: ['尼多王', 'Nidoking'],
    35: ['皮皮', 'Clefairy'],
    36: ['皮可西', 'Clefable'],
    37: ['六尾', 'Vulpix'],
    37001: ['六尾(阿罗拉)', 'Vulpix_a'],
    38: ['九尾', 'Ninetales'],
    38001: ['九尾(阿罗拉)', 'Ninetales_a'],
    39: ['胖丁', 'Jigglypuff'],
    40: ['胖可丁', 'Wigglytuff'],
    41: ['超音蝠', 'Zubat'],
    42: ['大嘴蝠', 'Golbat'],
    43: ['走路草', 'Oddish'],
    44: ['臭臭花', 'Gloom'],
    45: ['霸王花', 'Vileplume'],
    46: ['派拉斯', 'Paras'],
    47: ['派拉斯特', 'Parasect'],
    48: ['毛球', 'Venonat'],
    49: ['摩鲁蛾', 'Venomoth', '夫入蝶'],
    50: ['地鼠', 'Diglett'],
    50001: ['地鼠(阿罗拉)', 'Diglett_a'],
    51: ['三地鼠', 'Dugtrio'],
    51001: ['三地鼠(阿罗拉)', 'Dugtrio_a'],
    52: ['喵喵', 'Meowth'],
    52001: ['喵喵(阿罗拉)', 'Meowth_a'],
    52002: ['喵喵(伽勒尔)', 'Meowth_g'],
    53: ['猫老大', 'Persian'],
    53001: ['猫老大(阿罗拉)', 'Persian_a'],
    54: ['可达鸭', 'Psyduck'],
    55: ['哥达鸭', 'Golduck'],
    56: ['猴怪', 'Mankey'],
    57: ['火暴猴', 'Primeape'],
    58: ['卡蒂狗', 'Growlithe'],
    58003: ['卡蒂狗(洗翠)', 'Growlithe_x'],
    59: ['风速狗', 'Arcanine'],
    59003: ['风速狗(洗翠)', 'Arcanine_x'],
    60: ['蚊香蝌蚪', 'Poliwag'],
    61: ['蚊香君', 'Poliwhirl', '蚊香蛙'],
    62: ['蚊香泳士', 'Poliwrath', '快泳蛙'],
    63: ['凯西', 'Abra'],
    64: ['勇基拉', 'Kadabra'],
    65: ['胡地', 'Alakazam'],
    66: ['腕力', 'Machop'],
    67: ['豪力', 'Machoke'],
    68: ['怪力', 'Machamp'],
    69: ['喇叭芽', 'Bellsprout'],
    70: ['口呆花', 'Weepinbell'],
    71: ['大食花', 'Victreebel'],
    72: ['玛瑙水母', 'Tentacool'],
    73: ['毒刺水母', 'Tentacruel'],
    74: ['小拳石', 'Geodude'],
    74001: ['小拳石(阿罗拉)', 'Geodude_a'],
    75: ['隆隆石', 'Graveler'],
    75001: ['隆隆石(阿罗拉)', 'Graveler_a'],
    76: ['隆隆岩', 'Golem'],
    76001: ['隆隆岩(阿罗拉)', 'Golem_a'],
    77: ['小火马', 'Ponyta'],
    77002: ['小火马(伽勒尔)', 'Ponyta_g'],
    78: ['烈焰马', 'Rapidash'],
    78002: ['烈焰马(伽勒尔)', 'Rapidash_g'],
    79: ['呆呆兽', 'Slowpoke'],
    79002: ['呆呆兽(伽勒尔)', 'Slowpoke_g'],
    80: ['呆壳兽', 'Slowbro', '呆河马'],
    80002: ['呆壳兽(伽勒尔)', 'Slowbro_g', '伽勒尔呆河马'],
    81: ['小磁怪', 'Magnemite'],
    82: ['三合一磁怪', 'Magneton'],
    83: ['大葱鸭', 'Farfetch'],
    83002: ['大葱鸭(伽勒尔)', 'Farfetch_g'],
    84: ['嘟嘟', 'Doduo'],
    85: ['嘟嘟利', 'Dodrio'],
    86: ['小海狮', 'Seel'],
    87: ['白海狮', 'Dewgong'],
    88: ['臭泥', 'Grimer'],
    88001: ['臭泥(阿罗拉)', 'Grimer_a'],
    89: ['臭臭泥', 'Muk'],
    89001: ['臭臭泥(阿罗拉)', 'Muk_a'],
    90: ['大舌贝', 'Shellder'],
    91: ['刺甲贝', 'Cloyster', '铁甲贝'],
    92: ['鬼斯', 'Gastly'],
    93: ['鬼斯通', 'Haunter'],
    94: ['耿鬼', 'Gengar'],
    95: ['大岩蛇', 'Onix'],
    96: ['催眠貘', 'Drowzee', '素利普'],
    97: ['引梦貘人', 'Hypno', '素利拍'],
    98: ['大钳蟹', 'Krabby'],
    99: ['巨钳蟹', 'Kingler'],
    100: ['霹雳电球', 'Voltorb', '雷电球'],
    100003: ['霹雳电球(洗翠)', 'Voltorb_x', '洗翠雷电球'],
    101: ['顽皮雷弹', 'Electrode', '顽皮弹'],
    101003: ['顽皮雷弹(洗翠)', 'Electrode_x', '洗翠顽皮弹'],
    102: ['蛋蛋', 'Exeggcute'],
    103: ['椰蛋树', 'Exeggutor'],
    103001: ['椰蛋树(阿罗拉)', 'Exeggutor_a'],
    104: ['卡拉卡拉', 'Cubone'],
    105: ['嘎啦嘎啦', 'Marowak'],
    105001: ['嘎啦嘎啦(阿罗拉)', 'Marowak_a'],
    106: ['飞腿郎', 'Hitmonlee', '沙瓦郎'],
    107: ['快拳郎', 'Hitmonchan', '艾比郎'],
    108: ['大舌头', 'Lickitung'],
    109: ['瓦斯弹', 'Koffing'],
    110: ['双弹瓦斯', 'Weezing'],
    110002: ['双弹瓦斯(伽勒尔)', 'Weezing_g'],
    111: ['独角犀牛', 'Rhyhorn', '铁甲犀牛'],
    112: ['钻角犀兽', 'Rhydon', '铁甲暴龙'],
    113: ['吉利蛋', 'Chansey'],
    114: ['蔓藤怪', 'Tangela'],
    115: ['袋兽', 'Kangaskhan', '袋龙'],
    116: ['墨海马', 'Horsea'],
    117: ['海刺龙', 'Seadra'],
    118: ['角金鱼', 'Goldeen'],
    119: ['金鱼王', 'Seaking'],
    120: ['海星星', 'Staryu'],
    121: ['宝石海星', 'Starmie'],
    122: ['魔墙人偶', 'Mr. Mime', '吸盘魔偶'],
    122002: ['魔墙人偶(伽勒尔)', 'Mr. Mime_g', '伽勒尔吸盘魔偶'],
    123: ['飞天螳螂', 'Scyther'],
    124: ['迷唇姐', 'Jynx'],
    125: ['电击兽', 'Electabuzz'],
    126: ['鸭嘴火兽', 'Magmar'],
    127: ['凯罗斯', 'Pinsir', '大甲'],
    128: ['肯泰罗', 'Tauros'],
    128014: ['肯泰罗(斗战)', 'Tauros_pd'],
    128024: ['肯泰罗(火炽)', 'Tauros_ph'],
    128034: ['肯泰罗(水澜)', 'Tauros_ps'],
    129: ['鲤鱼王', 'Magikarp'],
    130: ['暴鲤龙', 'Gyarados'],
    131: ['拉普拉斯', 'Lapras', '乘龙'],
    132: ['百变怪', 'Ditto'],
    133: ['伊布', 'Eevee'],
    134: ['水伊布', 'Vaporeon'],
    135: ['雷伊布', 'Jolteon'],
    136: ['火伊布', 'Flareon'],
    137: ['多边兽', 'Porygon', '3D龙'],
    138: ['菊石兽', 'Omanyte'],
    139: ['多刺菊石兽', 'Omastar'],
    140: ['化石盔', 'Kabuto'],
    141: ['镰刀盔', 'Kabutops'],
    142: ['化石翼龙', 'Aerodactyl'],
    143: ['卡比兽', 'Snorlax'],
    144: ['急冻鸟', 'Articuno'],
    144002: ['急冻鸟(伽勒尔)', 'Articuno_g'],
    145: ['闪电鸟', 'Zapdos'],
    145002: ['闪电鸟(伽勒尔)', 'Zapdos_g'],
    146: ['火焰鸟', 'Moltres'],
    146002: ['火焰鸟(伽勒尔)', 'Moltres_g'],
    147: ['迷你龙', 'Dratini'],
    148: ['哈克龙', 'Dragonair'],
    149: ['快龙', 'Dragonite', '肥大'],
    150: ['超梦', 'Mewtwo'],
    151: ['梦幻', 'Mew'],
    152: ['菊草叶', 'Chikorita'],
    153: ['月桂叶', 'Bayleef'],
    154: ['大竺葵', 'Meganium', '大菊花'],
    155: ['火球鼠', 'Cyndaquil'],
    156: ['火岩鼠', 'Quilava'],
    157: ['火暴兽', 'Typhlosion'],
    157003: ['火暴兽(洗翠)', 'Typhlosion_x'],
    158: ['小锯鳄', 'Totodile'],
    159: ['蓝鳄', 'Croconaw'],
    160: ['大力鳄', 'Feraligatr'],
    161: ['尾立', 'Sentret'],
    162: ['大尾立', 'Furret'],
    163: ['咕咕', 'Hoothoot'],
    164: ['猫头夜鹰', 'Noctowl'],
    165: ['芭瓢虫', 'Ledyba'],
    166: ['安瓢虫', 'Ledian'],
    167: ['圆丝蛛', 'Spinarak'],
    168: ['阿利多斯', 'Ariados'],
    169: ['叉字蝠', 'Crobat'],
    170: ['灯笼鱼', 'Chinchou'],
    171: ['电灯怪', 'Lanturn'],
    172: ['皮丘', 'Pichu'],
    173: ['皮宝宝', 'Cleffa'],
    174: ['宝宝丁', 'Igglybuff'],
    175: ['波克比', 'Togepi'],
    176: ['波克基古', 'Togetic'],
    177: ['天然雀', 'Natu'],
    178: ['天然鸟', 'Xatu'],
    179: ['咩利羊', 'Mareep'],
    180: ['茸茸羊', 'Flaaffy', '绵绵'],
    181: ['电龙', 'Ampharos'],
    182: ['美丽花', 'Bellossom'],
    183: ['玛力露', 'Marill'],
    184: ['玛力露丽', 'Azumarill'],
    185: ['树才怪', 'Sudowoodo', '胡说树'],
    186: ['蚊香蛙皇', 'Politoed', '牛蛙君'],
    187: ['毽子草', 'Hoppip'],
    188: ['毽子花', 'Skiploom'],
    189: ['毽子棉', 'Jumpluff'],
    190: ['长尾怪手', 'Aipom'],
    191: ['向日种子', 'Sunkern'],
    192: ['向日花怪', 'Sunflora'],
    193: ['蜻蜻蜓', 'Yanma', '阳阳玛'],
    194: ['乌波', 'Wooper'],
    194004: ['乌波(帕底亚)', 'Wooper_p'],
    195: ['沼王', 'Quagsire'],
    196: ['太阳伊布', 'Espeon', '太阳精灵'],
    197: ['月亮伊布', 'Umbreon', '月精灵'],
    198: ['黑暗鸦', 'Murkrow'],
    199: ['呆呆王', 'Slowking', '河马王'],
    199002: ['呆呆王(伽勒尔)', 'Slowking_g', '伽勒尔河马王'],
    200: ['梦妖', 'Misdreavus'],
    201: ['未知图腾', 'Unown'],
    202: ['果然翁', 'Wobbuffet'],
    203: ['麒麟奇', 'Girafarig'],
    204: ['榛果球', 'Pineco'],
    205: ['佛烈托斯', 'Forretress'],
    206: ['土龙弟弟', 'Dunsparce'],
    207: ['天蝎', 'Gligar'],
    208: ['大钢蛇', 'Steelix'],
    209: ['布鲁', 'Snubbull'],
    210: ['布鲁皇', 'Granbull'],
    211: ['千针鱼', 'Qwilfish'],
    211003: ['千针鱼(洗翠)', 'Qwilfish_x'],
    212: ['巨钳螳螂', 'Scizor'],
    213: ['壶壶', 'Shuckle'],
    214: ['赫拉克罗斯', 'Heracross'],
    215: ['狃拉', 'Sneasel'],
    215003: ['狃拉(洗翠)', 'Sneasel_x'],
    216: ['熊宝宝', 'Teddiursa'],
    217: ['圈圈熊', 'Ursaring'],
    218: ['熔岩虫', 'Slugma'],
    219: ['熔岩蜗牛', 'Magcargo'],
    220: ['小山猪', 'Swinub'],
    221: ['长毛猪', 'Piloswine'],
    222: ['太阳珊瑚', 'Corsola'],
    222002: ['太阳珊瑚(伽勒尔)', 'Corsola_g'],
    223: ['铁炮鱼', 'Remoraid'],
    224: ['章鱼桶', 'Octillery'],
    225: ['信使鸟', 'Delibird'],
    226: ['巨翅飞鱼', 'Mantine'],
    227: ['盔甲鸟', 'Skarmory'],
    228: ['戴鲁比', 'Houndour'],
    229: ['黑鲁加', 'Houndoom'],
    230: ['刺龙王', 'Kingdra'],
    231: ['小小象', 'Phanpy'],
    232: ['顿甲', 'Donphan'],
    233: ['多边兽2', 'Porygon2', '3D龙2'],
    234: ['惊角鹿', 'Stantler'],
    235: ['图图犬', 'Smeargle'],
    236: ['无畏小子', 'Tyrogue', '巴尔郎'],
    237: ['战舞郎', 'Hitmontop', '柯波朗'],
    238: ['迷唇娃', 'Smoochum'],
    239: ['电击怪', 'Elekid'],
    240: ['鸭嘴宝宝', 'Magby'],
    241: ['大奶罐', 'Miltank'],
    242: ['幸福蛋', 'Blissey'],
    243: ['雷公', 'Raikou'],
    244: ['炎帝', 'Entei'],
    245: ['水君', 'Suicune'],
    246: ['幼基拉斯', 'Larvitar', '由基拉'],
    247: ['沙基拉斯', 'Pupitar', '沙基拉'],
    248: ['班基拉斯', 'Tyranitar', '班基拉'],
    249: ['洛奇亚', 'Lugia'],
    250: ['凤王', 'Ho-Oh','炸毛鸟'],
    251: ['时拉比', 'Celebi', '雪拉比'],
    252: ['木守宫', 'Treecko'],
    253: ['森林蜥蜴', 'Grovyle'],
    254: ['蜥蜴王', 'Sceptile'],
    255: ['火稚鸡', 'Torchic'],
    256: ['力壮鸡', 'Combusken'],
    257: ['火焰鸡', 'Blaziken'],
    258: ['水跃鱼', 'Mudkip'],
    259: ['沼跃鱼', 'Marshtomp'],
    260: ['巨沼怪', 'Swampert'],
    261: ['土狼犬', 'Poochyena'],
    262: ['大狼犬', 'Mightyena'],
    263002: ['蛇纹熊(伽勒尔)', 'Zigzagoon_g'],
    263: ['蛇纹熊', 'Zigzagoon'],
    264002: ['直冲熊(伽勒尔)', 'Linoone_g'],
    264: ['直冲熊', 'Linoone'],
    265: ['刺尾虫', 'Wurmple'],
    266: ['甲壳茧', 'Silcoon'],
    267: ['狩猎凤蝶', 'Beautifly'],
    268: ['盾甲茧', 'Cascoon'],
    269: ['毒粉蛾', 'Dustox'],
    270: ['莲叶童子', 'Lotad'],
    271: ['莲帽小童', 'Lombre'],
    272: ['乐天河童', 'Ludicolo'],
    273: ['橡实果', 'Seedot'],
    274: ['长鼻叶', 'Nuzleaf'],
    275: ['狡猾天狗', 'Shiftry'],
    276: ['傲骨燕', 'Taillow'],
    277: ['大王燕', 'Swellow'],
    278: ['长翅鸥', 'Wingull'],
    279: ['大嘴鸥', 'Pelipper'],
    280: ['拉鲁拉丝', 'Ralts'],
    281: ['奇鲁莉安', 'Kirlia'],
    282: ['沙奈朵', 'Gardevoir'],
    282101: ['超级沙奈朵', 'Gardevoir_m', 'mega沙奈朵'],
    283: ['溜溜糖球', 'Surskit'],
    284: ['雨翅蛾', 'Masquerain'],
    285: ['蘑蘑菇', 'Shroomish'],
    286: ['斗笠菇', 'Breloom'],
    287: ['懒人獭', 'Slakoth'],
    288: ['过动猿', 'Vigoroth'],
    289: ['请假王', 'Slaking'],
    290: ['土居忍士', 'Nincada'],
    291: ['铁面忍者', 'Ninjask'],
    292: ['脱壳忍者', 'Shedinja'],
    293: ['咕妞妞', 'Whismur'],
    294: ['吼爆弹', 'Loudred'],
    295: ['爆音怪', 'Exploud'],
    296: ['幕下力士', 'Makuhita'],
    297: ['铁掌力士', 'Hariyama', '超力王'],
    298: ['露力丽', 'Azurill'],
    299: ['朝北鼻', 'Nosepass'],
    300: ['向尾喵', 'Skitty'],
    301: ['优雅猫', 'Delcatty'],
    302: ['勾魂眼', 'Sableye'],
    303: ['大嘴娃', 'Mawile'],
    304: ['可可多拉', 'Aron'],
    305: ['可多拉', 'Lairon'],
    306: ['波士可多拉', 'Aggron'],
    307: ['玛沙那', 'Meditite'],
    308: ['恰雷姆', 'Medicham'],
    309: ['落雷兽', 'Electrike'],
    310: ['雷电兽', 'Manectric'],
    311: ['正电拍拍', 'Plusle'],
    312: ['负电拍拍', 'Minun'],
    313: ['电萤虫', 'Volbeat'],
    314: ['甜甜萤', 'Illumise'],
    315: ['毒蔷薇', 'Roselia'],
    316: ['溶食兽', 'Gulpin'],
    317: ['吞食兽', 'Swalot'],
    318: ['利牙鱼', 'Carvanha'],
    319: ['巨牙鲨', 'Sharpedo'],
    320: ['吼吼鲸', 'Wailmer'],
    321: ['吼鲸王', 'Wailord'],
    322: ['呆火驼', 'Numel'],
    323: ['喷火驼', 'Camerupt'],
    324: ['煤炭龟', 'Torkoal'],
    325: ['跳跳猪', 'Spoink'],
    326: ['噗噗猪', 'Grumpig'],
    327: ['晃晃斑', 'Spinda'],
    328: ['大颚蚁', 'Trapinch'],
    329: ['超音波幼虫', 'Vibrava'],
    330: ['沙漠蜻蜓', 'Flygon'],
    331: ['刺球仙人掌', 'Cacnea', '沙漠奈亚'],
    332: ['梦歌仙人掌', 'Cacturne', '梦哥奈亚'],
    333: ['青绵鸟', 'Swablu'],
    334: ['七夕青鸟', 'Altaria'],
    335: ['猫鼬斩', 'Zangoose'],
    336: ['饭匙蛇', 'Seviper'],
    337: ['月石', 'Lunatone'],
    338: ['太阳岩', 'Solrock'],
    339: ['泥泥鳅', 'Barboach'],
    340: ['鲶鱼王', 'Whiscash'],
    341: ['龙虾小兵', 'Corphish'],
    342: ['铁螯龙虾', 'Crawdaunt'],
    343: ['天秤偶', 'Baltoy'],
    344: ['念力土偶', 'Claydol'],
    345: ['触手百合', 'Lileep'],
    346: ['摇篮百合', 'Cradily'],
    347: ['太古羽虫', 'Anorith'],
    348: ['太古盔甲', 'Armaldo'],
    349: ['丑丑鱼', 'Feebas'],
    350: ['美纳斯', 'Milotic'],
    351: ['飘浮泡泡', 'Castform'],
    352: ['变隐龙', 'Kecleon'],
    353: ['怨影娃娃', 'Shuppet'],
    354: ['诅咒娃娃', 'Banette'],
    355: ['夜巡灵', 'Duskull', '夜骷颅'],
    356: ['彷徨夜灵', 'Dusclops', '夜巨人'],
    357: ['热带龙', 'Tropius'],
    358: ['风铃铃', 'Chimecho'],
    359: ['阿勃梭鲁', 'Absol'],
    360: ['小果然', 'Wynaut'],
    361: ['雪童子', 'Snorunt'],
    362: ['冰鬼护', 'Glalie'],
    363: ['海豹球', 'Spheal'],
    364: ['海魔狮', 'Sealeo'],
    365: ['帝牙海狮', 'Walrein'],
    366: ['珍珠贝', 'Clamperl'],
    367: ['猎斑鱼', 'Huntail'],
    368: ['樱花鱼', 'Gorebyss'],
    369: ['古空棘鱼', 'Relicanth'],
    370: ['爱心鱼', 'Luvdisc'],
    371: ['宝贝龙', 'Bagon'],
    372: ['甲壳龙', 'Shelgon'],
    373: ['暴飞龙', 'Salamence', '暴蝾螈', '血翼飞龙'],
    374: ['铁哑铃', 'Beldum'],
    375: ['金属怪', 'Metang'],
    376: ['巨金怪', 'Metagross'],
    377: ['雷吉洛克', 'Regirock', '岩柱', '岩神柱'],
    378: ['雷吉艾斯', 'Regice', '冰柱', '冰神柱'],
    379: ['雷吉斯奇鲁', 'Registeel', '钢柱', '钢神柱'],
    380: ['拉帝亚斯', 'Latias'],
    381: ['拉帝欧斯', 'Latios'],
    382: ['盖欧卡', 'Kyogre', '海皇牙','胖头鱼'],
    383: ['固拉多', 'Groudon', '古拉顿','不会飞'],
    384: ['烈空坐', 'Rayquaza', '超级绿毛虫'],
    385: ['基拉祈', 'Jirachi'],
    386: ['代欧奇希斯', 'Deoxys'],
    386101: ['代欧奇希斯(攻击)', 'Deoxys_a'],
    386102: ['代欧奇希斯(防御)', 'Deoxys_d'],
    386103: ['代欧奇希斯(速度)', 'Deoxys_s'],
    387: ['草苗龟', 'Turtwig'],
    388: ['树林龟', 'Grotle'],
    389: ['土台龟', 'Torterra'],
    390: ['小火焰猴', 'Chimchar', '小火猴'],
    391: ['猛火猴', 'Monferno'],
    392: ['烈焰猴', 'Infernape', '大师兄'],
    393: ['波加曼', 'Piplup'],
    394: ['波皇子', 'Prinplup'],
    395: ['帝王拿波', 'Empoleon'],
    396: ['姆克儿', 'Starly'],
    397: ['姆克鸟', 'Staravia'],
    398: ['姆克鹰', 'Staraptor', '发型鸟'],
    399: ['大牙狸', 'Bidoof'],
    400: ['大尾狸', 'Bibarel'],
    401: ['圆法师', 'Kricketot'],
    402: ['音箱蟀', 'Kricketune'],
    403: ['小猫怪', 'Shinx'],
    404: ['勒克猫', 'Luxio'],
    405: ['伦琴猫', 'Luxray'],
    406: ['含羞苞', 'Budew'],
    407: ['罗丝雷朵', 'Roserade'],
    408: ['头盖龙', 'Cranidos'],
    409: ['战槌龙', 'Rampardos'],
    410: ['盾甲龙', 'Shieldon'],
    411: ['护城龙', 'Bastiodon'],
    412: ['结草儿', 'Burmy'],
    413: ['结草贵妇', 'Wormadam'],
    414: ['绅士蛾', 'Mothim'],
    415: ['三蜜蜂', 'Combee'],
    416: ['蜂女王', 'Vespiquen'],
    417: ['帕奇利兹', 'Pachirisu'],
    418: ['泳圈鼬', 'Buizel'],
    419: ['浮潜鼬', 'Floatzel'],
    420: ['樱花宝', 'Cherubi'],
    421: ['樱花儿', 'Cherrim'],
    422: ['无壳海兔', 'Shellos'],
    423: ['海兔兽', 'Gastrodon'],
    424: ['双尾怪手', 'Ambipom'],
    425: ['飘飘球', 'Drifloon'],
    426: ['随风球', 'Drifblim'],
    427: ['卷卷耳', 'Buneary'],
    428: ['长耳兔', 'Lopunny'],
    429: ['梦妖魔', 'Mismagius'],
    430: ['乌鸦头头', 'Honchkrow'],
    431: ['魅力喵', 'Glameow'],
    432: ['东施喵', 'Purugly'],
    433: ['铃铛响', 'Chingling'],
    434: ['臭鼬噗', 'Stunky'],
    435: ['坦克臭鼬', 'Skuntank'],
    436: ['铜镜怪', 'Bronzor'],
    437: ['青铜钟', 'Bronzong'],
    438: ['盆才怪', 'Bonsly'],
    439: ['魔尼尼', 'Mime Jr.'],
    440: ['小福蛋', 'Happiny'],
    441: ['聒噪鸟', 'Chatot'],
    442: ['花岩怪', 'Spiritomb'],
    443: ['圆陆鲨', 'Gible'],
    444: ['尖牙陆鲨', 'Gabite'],
    445: ['烈咬陆鲨', 'Garchomp'],
    446: ['小卡比兽', 'Munchlax'],
    447: ['利欧路', 'Riolu'],
    448: ['路卡利欧', 'Lucario'],
    449: ['沙河马', 'Hippopotas'],
    450: ['河马兽', 'Hippowdon'],
    451: ['钳尾蝎', 'Skorupi'],
    452: ['龙王蝎', 'Drapion'],
    453: ['不良蛙', 'Croagunk'],
    454: ['毒骷蛙', 'Toxicroak'],
    455: ['尖牙笼', 'Carnivine'],
    456: ['荧光鱼', 'Finneon'],
    457: ['霓虹鱼', 'Lumineon'],
    458: ['小球飞鱼', 'Mantyke'],
    459: ['雪笠怪', 'Snover'],
    460: ['暴雪王', 'Abomasnow'],
    461: ['玛狃拉', 'Weavile'],
    462: ['自爆磁怪', 'Magnezone', 'UFO', 'ufo'],
    463: ['大舌舔', 'Lickilicky'],
    464: ['超甲狂犀', 'Rhyperior'],
    465: ['巨蔓藤', 'Tangrowth'],
    466: ['电击魔兽', 'Electivire'],
    467: ['鸭嘴炎兽', 'Magmortar'],
    468: ['波克基斯', 'Togekiss', '飞机', '波克鸟'],
    469: ['远古巨蜓', 'Yanmega'],
    470: ['叶伊布', 'Leafeon', '叶精灵'],
    471: ['冰伊布', 'Glaceon', '冰精灵'],
    472: ['天蝎王', 'Gliscor'],
    473: ['象牙猪', 'Mamoswine'],
    474: ['多边兽Z', 'Porygon-Z'],
    475: ['艾路雷朵', 'Gallade'],
    476: ['大朝北鼻', 'Probopass'],
    477: ['黑夜魔灵', 'Dusknoir'],
    478: ['雪妖女', 'Froslass'],
    479: ['洛托姆', 'Rotom'],
    479101: ['加热洛托姆', 'Rotom_jr'],
    479102: ['清洗洛托姆', 'Rotom_qx'],
    479103: ['结冰洛托姆', 'Rotom_jb'],
    479104: ['旋转洛托姆', 'Rotom_xz'],
    479105: ['切割洛托姆', 'Rotom_qg'],
    480: ['由克希', 'Uxie'],
    481: ['艾姆利多', 'Mesprit'],
    482: ['亚克诺姆', 'Azelf'],
    483: ['帝牙卢卡', 'Dialga'],
    483101: ['帝牙卢卡(起源)', 'Dialga_o'],
    484: ['帕路奇亚', 'Palkia'],
    484101: ['帕路奇亚(起源)', 'Palkia_o'],
    485: ['席多蓝恩', 'Heatran'],
    486: ['雷吉奇卡斯', 'Regigigas', '神柱王'],
    487: ['骑拉帝纳', 'Giratina', '冥王龙'],
    487101: ['骑拉帝纳(起源)', 'Giratina_o', '冥王龙(起源)'],
    488: ['克雷色利亚', 'Cresselia', '美梦神'],
    489: ['霏欧纳', 'Phione'],
    490: ['玛纳霏', 'Manaphy'],
    491: ['达克莱伊', 'Darkrai', '噩梦神'],
    492: ['谢米', 'Shaymin', '雪米'],
    492101: ['谢米(天空)', 'Shaymin_t', '雪米(天空)'],
    493: ['阿尔宙斯', 'Arceus', '羊驼', '创世神'],
    494: ['比克提尼', 'Victini'],
    495: ['藤藤蛇', 'Snivy'],
    496: ['青藤蛇', 'Servine'],
    497: ['君主蛇', 'Serperior'],
    498: ['暖暖猪', 'Tepig'],
    499: ['炒炒猪', 'Pignite'],
    500: ['炎武王', 'Emboar', '二师兄'],
    501: ['水水獭', 'Oshawott'],
    502: ['双刃丸', 'Dewott'],
    503: ['大剑鬼', 'Samurott'],
    503003: ['大剑鬼(洗翠)', 'Samurott_x'],
    504: ['探探鼠', 'Patrat'],
    505: ['步哨鼠', 'Watchog'],
    506: ['小约克', 'Lillipup'],
    507: ['哈约克', 'Herdier'],
    508: ['长毛狗', 'Stoutland'],
    509: ['扒手猫', 'Purrloin'],
    510: ['酷豹', 'Liepard'],
    511: ['花椰猴', 'Pansage'],
    512: ['花椰猿', 'Simisage'],
    513: ['爆香猴', 'Pansear'],
    514: ['爆香猿', 'Simisear'],
    515: ['冷水猴', 'Panpour'],
    516: ['冷水猿', 'Simipour'],
    517: ['食梦梦', 'Munna'],
    518: ['梦梦蚀', 'Musharna'],
    519: ['豆豆鸽', 'Pidove'],
    520: ['咕咕鸽', 'Tranquill'],
    521: ['高傲雉鸡', 'Unfezant'],
    522: ['斑斑马', 'Blitzle'],
    523: ['雷电斑马', 'Zebstrika'],
    524: ['石丸子', 'Roggenrola'],
    525: ['地幔岩', 'Boldore'],
    526: ['庞岩怪', 'Gigalith'],
    527: ['滚滚蝙蝠', 'Woobat'],
    528: ['心蝙蝠', 'Swoobat'],
    529: ['螺钉地鼠', 'Drilbur'],
    530: ['龙头地鼠', 'Excadrill'],
    531: ['差不多娃娃', 'Audino'],
    532: ['搬运小匠', 'Timburr'],
    533: ['铁骨土人', 'Gurdurr'],
    534: ['修建老匠', 'Conkeldurr'],
    535: ['圆蝌蚪', 'Tympole'],
    536: ['蓝蟾蜍', 'Palpitoad'],
    537: ['蟾蜍王', 'Seismitoad'],
    538: ['投摔鬼', 'Throh'],
    539: ['打击鬼', 'Sawk'],
    540: ['虫宝包', 'Sewaddle'],
    541: ['宝包茧', 'Swadloon'],
    542: ['保姆虫', 'Leavanny'],
    543: ['百足蜈蚣', 'Venipede'],
    544: ['车轮球', 'Whirlipede'],
    545: ['蜈蚣王', 'Scolipede'],
    546: ['木棉球', 'Cottonee'],
    547: ['风妖精', 'Whimsicott'],
    548: ['百合根娃娃', 'Petilil'],
    549: ['裙儿小姐', 'Lilligant'],
    549003: ['裙儿小姐(洗翠)', 'Lilligant_x'],
    550: ['野蛮鲈鱼', 'Basculin'],
    551: ['黑眼鳄', 'Sandile'],
    552: ['混混鳄', 'Krokorok'],
    553: ['流氓鳄', 'Krookodile'],
    554: ['火红不倒翁', 'Darumaka'],
    554002: ['火红不倒翁(伽勒尔)', 'Darumaka_g'],
    555: ['达摩狒狒', 'Darmanitan'],
    555002: ['达摩狒狒(伽勒尔)', 'Darmanitan_g'],
    556: ['沙铃仙人掌', 'Maractus'],
    557: ['石居蟹', 'Dwebble'],
    558: ['岩殿居蟹', 'Crustle'],
    559: ['滑滑小子', 'Scraggy'],
    560: ['头巾混混', 'Scrafty'],
    561: ['象征鸟', 'Sigilyph'],
    562: ['哭哭面具', 'Yamask'],
    562002: ['哭哭面具(伽勒尔)', 'Yamask_g'],
    563: ['死神棺', 'Cofagrigus'],
    564: ['原盖海龟', 'Tirtouga'],
    565: ['肋骨海龟', 'Carracosta'],
    566: ['始祖小鸟', 'Archen'],
    567: ['始祖大鸟', 'Archeops'],
    568: ['破破袋', 'Trubbish'],
    569: ['灰尘山', 'Garbodor'],
    570: ['索罗亚', 'Zorua'],
    570003: ['索罗亚(洗翠)', 'Zorua_x'],
    571: ['索罗亚克', 'Zoroark'],
    571003: ['索罗亚克(洗翠)', 'Zoroark_x'],
    572: ['泡沫栗鼠', 'Minccino'],
    573: ['奇诺栗鼠', 'Cinccino'],
    574: ['哥德宝宝', 'Gothita'],
    575: ['哥德小童', 'Gothorita'],
    576: ['哥德小姐', 'Gothitelle'],
    577: ['单卵细胞球', 'Solosis'],
    578: ['双卵细胞球', 'Duosion'],
    579: ['人造细胞卵', 'Reuniclus'],
    580: ['鸭宝宝', 'Ducklett'],
    581: ['舞天鹅', 'Swanna'],
    582: ['迷你冰', 'Vanillite'],
    583: ['多多冰', 'Vanillish'],
    584: ['双倍多多冰', 'Vanilluxe'],
    585: ['四季鹿', 'Deerling'],
    586: ['萌芽鹿', 'Sawsbuck'],
    587: ['电飞鼠', 'Emolga'],
    588: ['盖盖虫', 'Karrablast'],
    589: ['骑士蜗牛', 'Escavalier'],
    590: ['哎呀球菇', 'Foongus'],
    591: ['败露球菇', 'Amoonguss'],
    592: ['轻飘飘', 'Frillish'],
    593: ['胖嘟嘟', 'Jellicent'],
    594: ['保姆曼波', 'Alomomola'],
    595: ['电电虫', 'Joltik'],
    596: ['电蜘蛛', 'Galvantula'],
    597: ['种子铁球', 'Ferroseed'],
    598: ['坚果哑铃', 'Ferrothorn'],
    599: ['齿轮儿', 'Klink'],
    600: ['齿轮组', 'Klang'],
    601: ['齿轮怪', 'Klinklang'],
    602: ['麻麻小鱼', 'Tynamo'],
    603: ['麻麻鳗', 'Eelektrik'],
    604: ['麻麻鳗鱼王', 'Eelektross'],
    605: ['小灰怪', 'Elgyem'],
    606: ['大宇怪', 'Beheeyem'],
    607: ['烛光灵', 'Litwick'],
    608: ['灯火幽灵', 'Lampent'],
    609: ['水晶灯火灵', 'Chandelure'],
    610: ['牙牙', 'Axew'],
    611: ['斧牙龙', 'Fraxure'],
    612: ['双斧战龙', 'Haxorus'],
    613: ['喷嚏熊', 'Cubchoo'],
    614: ['冻原熊', 'Beartic'],
    615: ['几何雪花', 'Cryogonal'],
    616: ['小嘴蜗', 'Shelmet'],
    617: ['敏捷虫', 'Accelgor'],
    618: ['泥巴鱼', 'Stunfisk'],
    618002: ['泥巴鱼(伽勒尔)', 'Stunfisk_g'],
    619: ['功夫鼬', 'Mienfoo'],
    620: ['师父鼬', 'Mienshao'],
    621: ['赤面龙', 'Druddigon'],
    622: ['泥偶小人', 'Golett'],
    623: ['泥偶巨人', 'Golurk'],
    624: ['驹刀小兵', 'Pawniard'],
    625: ['劈斩司令', 'Bisharp'],
    626: ['爆炸头水牛', 'Bouffalant'],
    627: ['毛头小鹰', 'Rufflet'],
    628: ['勇士雄鹰', 'Braviary'],
    628003: ['勇士雄鹰(洗翠)', 'Braviary_x'],
    629: ['秃鹰丫头', 'Vullaby'],
    630: ['秃鹰娜', 'Mandibuzz'],
    631: ['熔蚁兽', 'Heatmor'],
    632: ['铁蚁', 'Durant'],
    633: ['单首龙', 'Deino'],
    634: ['双首暴龙', 'Zweilous'],
    635: ['三首恶龙', 'Hydreigon'],
    636: ['燃烧虫', 'Larvesta'],
    637: ['火神蛾', 'Volcarona'],
    638: ['勾帕路翁', 'Cobalion'],
    639: ['代拉基翁', 'Terrakion'],
    640: ['毕力吉翁', 'Virizion'],
    641: ['龙卷云', 'Tornadus'],
    641101: ['龙卷云(灵兽)', 'Tornadus_o'],
    642: ['雷电云', 'Thundurus'],
    642101: ['雷电云(灵兽)', 'Thundurus_o'],
    643: ['莱希拉姆', 'Reshiram'],
    644: ['捷克罗姆', 'Zekrom'],
    645: ['土地云', 'Landorus'],
    645101: ['土地云(灵兽)', 'Landorus_o'],
    646: ['酋雷姆', 'Kyurem'],
    646001: ['暗黑酋雷姆', 'Kyurem'],
    646002: ['焰白酋雷姆', 'Kyurem'],
    647: ['凯路迪欧', 'Keldeo'],
    648: ['美洛耶塔', 'Meloetta'],
    649: ['盖诺赛克特', 'Genesect'],
    650: ['哈力栗', 'Chespin'],
    651: ['胖胖哈力', 'Quilladin'],
    652: ['布里卡隆', 'Chesnaught'],
    653: ['火狐狸', 'Fennekin'],
    654: ['长尾火狐', 'Braixen'],
    655: ['妖火红狐', 'Delphox'],
    656: ['呱呱泡蛙', 'Froakie'],
    657: ['呱头蛙', 'Frogadier'],
    658: ['甲贺忍蛙', 'Greninja'],
    659: ['掘掘兔', 'Bunnelby'],
    660: ['掘地兔', 'Diggersby'],
    661: ['小箭雀', 'Fletchling'],
    662: ['火箭雀', 'Fletchinder'],
    663: ['烈箭鹰', 'Talonflame'],
    664: ['粉蝶虫', 'Scatterbug'],
    665: ['粉蝶蛹', 'Spewpa'],
    666: ['彩粉蝶', 'Vivillon'],
    667: ['小狮狮', 'Litleo'],
    668: ['火炎狮', 'Pyroar'],
    669: ['花蓓蓓', 'Flabébé'],
    670: ['花叶蒂', 'Floette'],
    671: ['花洁夫人', 'Florges'],
    672: ['坐骑小羊', 'Skiddo'],
    673: ['坐骑山羊', 'Gogoat'],
    674: ['顽皮熊猫', 'Pancham'],
    675: ['流氓熊猫', 'Pangoro'],
    676: ['多丽米亚', 'Furfrou'],
    677: ['妙喵', 'Espurr'],
    678: ['超能妙喵', 'Meowstic'],
    679: ['独剑鞘', 'Honedge'],
    680: ['双剑鞘', 'Doublade'],
    681: ['坚盾剑怪', 'Aegislash'],
    682: ['粉香香', 'Spritzee'],
    683: ['芳香精', 'Aromatisse'],
    684: ['绵绵泡芙', 'Swirlix'],
    685: ['胖甜妮', 'Slurpuff'],
    686: ['好啦鱿', 'Inkay'],
    687: ['乌贼王', 'Malamar'],
    688: ['龟脚脚', 'Binacle'],
    689: ['龟足巨铠', 'Barbaracle'],
    690: ['垃垃藻', 'Skrelp'],
    691: ['毒藻龙', 'Dragalge'],
    692: ['铁臂枪虾', 'Clauncher'],
    693: ['钢炮臂虾', 'Clawitzer'],
    694: ['伞电蜥', 'Helioptile'],
    695: ['光电伞蜥', 'Heliolisk'],
    696: ['宝宝暴龙', 'Tyrunt'],
    697: ['怪颚龙', 'Tyrantrum'],
    698: ['冰雪龙', 'Amaura'],
    699: ['冰雪巨龙', 'Aurorus'],
    700: ['仙子伊布', 'Sylveon'],
    701: ['摔角鹰人', 'Hawlucha'],
    702: ['咚咚鼠', 'Dedenne'],
    703: ['小碎钻', 'Carbink'],
    704: ['黏黏宝', 'Goomy'],
    705: ['黏美儿', 'Sliggoo'],
    705003: ['黏美儿(洗翠)', 'Sliggoo_x'],
    706: ['黏美龙', 'Goodra'],
    706003: ['黏美龙(洗翠)', 'Goodra_x'],
    707: ['钥圈儿', 'Klefki'],
    708: ['小木灵', 'Phantump'],
    709: ['朽木妖', 'Trevenant'],
    710: ['南瓜精', 'Pumpkaboo'],
    711: ['南瓜怪人', 'Gourgeist'],
    712: ['冰宝', 'Bergmite'],
    713: ['冰岩怪', 'Avalugg'],
    713003: ['冰岩怪(洗翠)', 'Avalugg_x'],
    714: ['嗡蝠', 'Noibat'],
    715: ['音波龙', 'Noivern'],
    716: ['哲尔尼亚斯', 'Xerneas'],
    717: ['伊裴尔塔尔', 'Yveltal'],
    718: ['基格尔德', 'Zygarde'],
    719: ['蒂安希', 'Diancie'],
    720: ['胡帕', 'Hoopa'],
    720101: ['解放胡帕', 'Hoopa_j'],
    721: ['波尔凯尼恩', 'Volcanion'],
    722: ['木木枭', 'Rowlet', '南小鸟'],
    723: ['投羽枭', 'Dartrix'],
    724: ['狙射树枭', 'Decidueye'],
    724003: ['狙射树枭(洗翠)', 'Decidueye_x'],
    725: ['火斑喵', 'Litten'],
    726: ['炎热喵', 'Torracat'],
    727: ['炽焰咆哮虎', 'Incineroar'],
    728: ['球球海狮', 'Popplio'],
    729: ['花漾海狮', 'Brionne'],
    730: ['西狮海壬', 'Primarina'],
    731: ['小笃儿', 'Pikipek'],
    732: ['喇叭啄鸟', 'Trumbeak'],
    733: ['铳嘴大鸟', 'Toucannon'],
    734: ['猫鼬少', 'Yungoos'],
    735: ['猫鼬探长', 'Gumshoos'],
    736: ['强颚鸡母虫', 'Grubbin'],
    737: ['虫电宝', 'Charjabug'],
    738: ['锹农炮虫', 'Vikavolt'],
    739: ['好胜蟹', 'Crabrawler'],
    740: ['好胜毛蟹', 'Crabominable'],
    741: ['花舞鸟', 'Oricorio'],
    742: ['萌虻', 'Cutiefly'],
    743: ['蝶结萌虻', 'Ribombee'],
    744: ['岩狗狗', 'Rockruff'],
    745: ['鬃岩狼人', 'Lycanroc'],
    746: ['弱丁鱼', 'Wishiwashi'],
    747: ['好坏星', 'Mareanie'],
    748: ['超坏星', 'Toxapex'],
    749: ['泥驴仔', 'Mudbray'],
    750: ['重泥挽马', 'Mudsdale'],
    751: ['滴蛛', 'Dewpider'],
    752: ['滴蛛霸', 'Araquanid'],
    753: ['伪螳草', 'Fomantis'],
    754: ['兰螳花', 'Lurantis'],
    755: ['睡睡菇', 'Morelull'],
    756: ['灯罩夜菇', 'Shiinotic'],
    757: ['夜盗火蜥', 'Salandit'],
    758: ['焰后蜥', 'Salazzle'],
    759: ['童偶熊', 'Stufful'],
    760: ['穿着熊', 'Bewear'],
    761: ['甜竹竹', 'Bounsweet'],
    762: ['甜舞妮', 'Steenee'],
    763: ['甜冷美后', 'Tsareena'],
    764: ['花疗环环', 'Comfey'],
    765: ['智挥猩', 'Oranguru'],
    766: ['投掷猴', 'Passimian'],
    767: ['胆小虫', 'Wimpod'],
    768: ['具甲武者', 'Golisopod'],
    769: ['沙丘娃', 'Sandygast'],
    770: ['噬沙堡爷', 'Palossand'],
    771: ['拳海参', 'Pyukumuku'],
    772: ['属性空', 'Type:Null'],
    773: ['银伴战兽', 'Silvally'],
    774: ['小陨星', 'Minior'],
    775: ['树枕尾熊', 'Komala'],
    776: ['爆焰龟兽', 'Turtonator'],
    777: ['托戈德玛尔', 'Togedemaru'],
    778: ['谜拟丘', 'Mimikyu'],
    779: ['磨牙彩皮鱼', 'Bruxish'],
    780: ['老翁龙', 'Drampa'],
    781: ['破破舵轮', 'Dhelmise'],
    782: ['心鳞宝', 'Jangmo-o'],
    783: ['鳞甲龙', 'Hakamo-o'],
    784: ['杖尾鳞甲龙', 'Kommo-o'],
    785: ['卡璞鸣鸣', 'Tapu Koko', '鸣鸣'],
    786: ['卡璞蝶蝶', 'Tapu Lele', '蝶蝶'],
    787: ['卡璞哞哞', 'Tapu Bulu', '哞哞'],
    788: ['卡璞鳍鳍', 'Tapu Fini', '鳍鳍'],
    789: ['科斯莫古', 'Cosmog'],
    790: ['科斯莫姆', 'Cosmoem'],
    791: ['索尔迦雷欧', 'Solgaleo', '日神'],
    792: ['露奈雅拉', 'Lunala', '月神'],
    793: ['虚吾伊德', 'Nihilego'],
    794: ['爆肌蚊', 'Buzzwole'],
    795: ['费洛美螂', 'Pheromosa'],
    796: ['电束木', 'Xurkitree'],
    797: ['铁火辉夜', 'Celesteela'],
    798: ['纸御剑', 'Kartana'],
    799: ['恶食大王', 'Guzzlord'],
    800: ['奈克洛兹玛', 'Necrozma'],
    800101: ['黄昏之鬃', 'Necrozma_s'],
    800102: ['拂晓之翼', 'Necrozma_l'],
    800103: ['究极奈克洛兹玛', 'Necrozma_j'],
    801: ['玛机雅娜', 'Magearna'],
    802: ['玛夏多', 'Marshadow'],
    803: ['毒贝比', 'Poipole'],
    804: ['四颚针龙', 'Naganadel'],
    805: ['垒磊石', 'Stakataka'],
    806: ['砰头小丑', 'Blacephalon'],
    807: ['捷拉奥拉', 'Zeraora'],
    808: ['美录坦', 'Meltan'],
    809: ['美录梅塔', 'Melmetal'],
    810: ['敲音猴', 'Grookey'],
    811: ['啪咚猴', 'Thwackey'],
    812: ['轰擂金刚猩', 'Rillaboom'],
    813: ['炎兔儿', 'Scorbunny'],
    814: ['腾蹴小将', 'Raboot'],
    815: ['闪焰王牌', 'Cinderace'],
    816: ['泪眼蜥', 'Sobble'],
    817: ['变涩蜥', 'Drizzile'],
    818: ['千面避役', 'Inteleon'],
    819: ['贪心栗鼠', 'Skwovet'],
    820: ['藏饱栗鼠', 'Greedent'],
    821: ['稚山雀', 'Rookidee'],
    822: ['蓝鸦', 'Corvisquire'],
    823: ['钢铠鸦', 'Corviknight'],
    824: ['索侦虫', 'Blipbug'],
    825: ['天罩虫', 'Dottler'],
    826: ['以欧路普', 'Orbeetle'],
    827: ['偷儿狐', 'Nickit'],
    828: ['狐大盗', 'Thievul'],
    829: ['幼棉棉', 'Gossifleur'],
    830: ['白蓬蓬', 'Eldegoss'],
    831: ['毛辫羊', 'Wooloo'],
    832: ['毛毛角羊', 'Dubwool'],
    833: ['咬咬龟', 'Chewtle'],
    834: ['暴噬龟', 'Drednaw'],
    835: ['来电汪', 'Yamper'],
    836: ['逐电犬', 'Boltund'],
    837: ['小炭仔', 'Rolycoly'],
    838: ['大炭车', 'Carkol'],
    839: ['巨炭山', 'Coalossal'],
    840: ['啃果虫', 'Applin'],
    841: ['苹裹龙', 'Flapple'],
    842: ['丰蜜龙', 'Appletun'],
    843: ['沙包蛇', 'Silicobra'],
    844: ['沙螺蟒', 'Sandaconda'],
    845: ['古月鸟', 'Cramorant'],
    846: ['刺梭鱼', 'Arrokuda'],
    847: ['戽斗尖梭', 'Barraskewda'],
    848: ['毒电婴', 'Toxel'],
    849: ['颤弦蝾螈', 'Toxtricity'],
    850: ['烧火蚣', 'Sizzlipede'],
    851: ['焚焰蚣', 'Centiskorch'],
    852: ['拳拳蛸', 'Clobbopus'],
    853: ['八爪武师', 'Grapploct'],
    854: ['来悲茶', 'Sinistea'],
    855: ['怖思壶', 'Polteageist'],
    856: ['迷布莉姆', 'Hatenna'],
    857: ['提布莉姆', 'Hattrem'],
    858: ['布莉姆温', 'Hatterene'],
    859: ['捣蛋小妖', 'Impidimp'],
    860: ['诈唬魔', 'Morgrem'],
    861: ['长毛巨魔', 'Grimmsnarl'],
    862: ['堵拦熊', 'Obstagoon'],
    863: ['喵头目', 'Perrserker'],
    864: ['魔灵珊瑚', 'Cursola'],
    865: ['葱游兵', 'Sirfetch’d'],
    866: ['踏冰人偶', 'Mr. Rime'],
    867: ['死神板', 'Runerigus'],
    868: ['小仙奶', 'Milcery'],
    869: ['霜奶仙', 'Alcremie'],
    870: ['列阵兵', 'Falinks'],
    871: ['啪嚓海胆', 'Pincurchin'],
    872: ['雪吞虫', 'Snom'],
    873: ['雪绒蛾', 'Frosmoth'],
    874: ['巨石丁', 'Stonjourner'],
    875: ['冰砌鹅', 'Eiscue'],
    876: ['爱管侍', 'Indeedee'],
    877: ['莫鲁贝可', 'Morpeko'],
    878: ['铜象', 'Cufant'],
    879: ['大王铜象', 'Copperajah'],
    880: ['雷鸟龙', 'Dracozolt'],
    881: ['雷鸟海兽', 'Arctozolt'],
    882: ['鳃鱼龙', 'Dracovish'],
    883: ['鳃鱼海兽', 'Arctovish'],
    884: ['铝钢龙', 'Duraludon'],
    885: ['多龙梅西亚', 'Dreepy'],
    886: ['多龙奇', 'Drakloak'],
    887: ['多龙巴鲁托', 'Dragapult'],
    888: ['苍响', 'Zacian'],
    888001: ['苍响(剑之王)', 'Zacian'],
    889: ['藏玛然特', 'Zamazenta'],
    890: ['无极汰那', 'Eternatus'],
    891: ['熊徒弟', 'Kubfu'],
    892: ['武道熊师(一击)', 'Urshifu'],
    892101: ['武道熊师(连击)', 'Urshifu_y'],
    893: ['萨戮德', 'Zarude'],
    894: ['雷吉艾勒奇', 'Regieleki', '电柱', '雷柱'],
    895: ['雷吉铎拉戈', 'Regidrago', '龙柱'],
    896: ['雪暴马', 'Glastrier'],
    897: ['灵幽马', 'Spectrier'],
    898: ['蕾冠王', 'Calyrex'],
    898001: ['蕾冠王(白马)', 'Calyrex'],
    898002: ['蕾冠王(黑马)', 'Calyrex'],
    899: ['诡角鹿', 'Wyrdeer'],
    900: ['劈斧螳螂', 'Kleavor'],
    901: ['月月熊', 'Ursaluna'],
    902: ['幽尾玄鱼', 'Basculegion'],
    903: ['大狃拉', 'Sneasler'],
    904: ['万针鱼', 'Overqwil'],
    905: ['眷恋云', 'Enamorus'],
    906: ['新叶喵', 'Sprigatito'],
    907: ['蒂蕾喵', 'Floragato'],
    908: ['魔幻假面喵', 'Meowscarada'],
    909: ['呆火鳄', 'Fuecoco'],
    910: ['炙烫鳄', 'Crocalor'],
    911: ['骨纹巨声鳄', 'Skeledirge'],
    912: ['润水鸭', 'Quaxly'],
    913: ['涌跃鸭', 'Quaxwell'],
    914: ['狂欢浪舞鸭', 'Quaquaval'],
    915: ['爱吃豚', 'Lechonk'],
    916: ['飘香豚', 'Oinkologne'],
    917: ['团珠蛛', 'Tarountula'],
    918: ['操陷蛛', 'Spidops'],
    919: ['豆蟋蟀', 'Nymble'],
    920: ['烈腿蝗', 'Lokix'],
    921: ['布拨', 'Pawmi'],
    922: ['布土拨', 'Pawmo'],
    923: ['巴布土拨', 'Pawmot'],
    924: ['一对鼠', 'Tandemaus'],
    925: ['一家鼠', 'Maushold'],
    926: ['狗仔包', 'Fidough'],
    927: ['麻花犬', 'Dachsbun'],
    928: ['迷你芙', 'Smoliv'],
    929: ['奥利纽', 'Dolliv'],
    930: ['奥利瓦', 'Arboliva'],
    931: ['怒鹦哥', 'Squawkabilly'],
    932: ['盐石宝', 'Nacli'],
    933: ['盐石垒', 'Naclstack'],
    934: ['盐石巨灵', 'Garganacl'],
    935: ['炭小侍', 'Charcadet'],
    936: ['红莲铠骑', 'Armarouge'],
    937: ['苍炎刃鬼', 'Ceruledge'],
    938: ['光蚪仔', 'Tadbulb'],
    939: ['电肚蛙', 'Bellibolt'],
    940: ['电海燕', 'Wattrel'],
    941: ['大电海燕', 'Kilowattrel'],
    942: ['偶叫獒', 'Maschiff'],
    943: ['獒教父', 'Mabosstiff'],
    944: ['滋汁鼹', 'Shroodle'],
    945: ['涂标客', 'Grafaiai'],
    946: ['纳噬草', 'Bramblin'],
    947: ['怖纳噬草', 'Brambleghast'],
    948: ['原野水母', 'Toedscool'],
    949: ['陆地水母', 'Toedscruel'],
    950: ['毛崖蟹', 'Klawf'],
    951: ['热辣娃', 'Capsakid'],
    952: ['狠辣椒', 'Scovillain'],
    953: ['虫滚泥', 'Rellor'],
    954: ['虫甲圣', 'Rabsca'],
    955: ['飘飘雏', 'Flittle'],
    956: ['超能艳鸵', 'Espathra'],
    957: ['小锻匠', 'Tinkatink'],
    958: ['巧锻匠', 'Tinkatuff'],
    959: ['巨锻匠', 'Tinkaton'],
    960: ['海地鼠', 'Wiglett'],
    961: ['三海地鼠', 'Wugtrio'],
    962: ['下石鸟', 'Bombirdier'],
    963: ['波普海豚', 'Finizen'],
    964: ['海豚侠', 'Palafin'],
    965: ['噗隆隆', 'Varoom'],
    966: ['普隆隆姆', 'Revavroom'],
    967: ['摩托蜥', 'Cyclizar'],
    968: ['拖拖蚓', 'Orthworm'],
    969: ['晶光芽', 'Glimmet'],
    970: ['晶光花', 'Glimmora'],
    971: ['墓仔狗', 'Greavard'],
    972: ['墓扬犬', 'Houndstone'],
    973: ['缠红鹤', 'Flamigo'],
    974: ['走鲸', 'Cetoddle'],
    975: ['浩大鲸', 'Cetitan'],
    976: ['轻身鳕', 'Veluza'],
    977: ['吃吼霸', 'Dondozo'],
    978: ['米立龙', 'Tatsugiri'],
    979: ['弃世猴', 'Annihilape'],
    980: ['土王', 'Clodsire'],
    981: ['奇麒麟', 'Farigiraf'],
    982: ['土龙节节', 'Dudunsparce'],
    983: ['仆斩将军', 'Kingambit'],
    984: ['雄伟牙', 'Great Tusk'],
    985: ['吼叫尾', 'Scream Tail'],
    986: ['猛恶菇', 'Brute Bonnet'],
    987: ['振翼发', 'Flutter Mane'],
    988: ['爬地翅', 'Slither Wing'],
    989: ['沙铁皮', 'Sandy Shocks'],
    990: ['铁辙迹', 'Iron Treads'],
    991: ['铁包袱', 'Iron Bundle'],
    992: ['铁臂膀', 'Iron Hands'],
    993: ['铁脖颈', 'Iron Jugulis'],
    994: ['铁毒蛾', 'Iron Moth'],
    995: ['铁荆棘', 'Iron Thorns'],
    996: ['凉脊龙', 'Frigibax'],
    997: ['冻脊龙', 'Arctibax'],
    998: ['戟脊龙', 'Baxcalibur'],
    999: ['索财灵', 'Gimmighoul'],
    1000: ['赛富豪', 'Gholdengo'],
    1001: ['古简蜗', 'Wo-Chien'],
    1002: ['古剑豹', 'Chien-Pao'],
    1003: ['古鼎鹿', 'Ting-Lu'],
    1004: ['古玉鱼', 'Chi-Yu'],
    1005: ['轰鸣月', 'Roaring Moon'],
    1006: ['铁武者', 'Iron Valiant'],
    1007: ['故勒顿', 'Koraidon'],
    1008: ['密勒顿', 'Miraidon'],
    1009: ['波荡水', 'Walking Wake'],
    1010: ['铁斑叶', 'Iron Leaves'],
    1011: ['裹蜜虫',],
    1012: ['斯魔茶',],
    1013: ['来悲粗茶'],
    1014: ['够赞狗','Okidogi'],
    1015: ['愿增猿','Munkidori'],
    1016: ['吉雉鸡','Fezandipiti'],
    1017: ['厄诡椪','Ogerpon'],
    1018: ['铝钢桥龙','Archaludon'],
    1019: ['蜜集大蛇','Hydrapple'],
    1020: ['破空焰','Gouging Fire'],
    1021: ['猛雷鼓','Raging Bolt'],
    1022: ['铁磐岩','Iron Boulder'],
    1023: ['铁头壳','Iron Crown'],
    1024: ['太乐巴戈斯','Terapagos'],
    1025: ['桃歹郎','Pecharunt'],
}
